name: test
on: push

jobs:
  test:
    name: Test with RSpec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        docker-compose run -it app rake db:create
        docker-compose run -it app rake db:migrate
    - name: Exec RSpec
      run: |
        docker-compose run -it app bundle exec rspec
