name: test
on: push

jobs:
  test:
    name: Test with RSpec
    runs-on: ubuntu-latest
    # 参考：https://codelabo.com/posts/20201128164634
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      shell: bash
      run: |
        docker-compose build
        docker-compose up -d db
        docker-compose ps
        docker-compose logs db
        docker-compose run app rake db:create
        docker-compose run app rake db:migrate
      env:
        RAILS_ENV: test
    - name: Exec RSpec
      shell: bash
      run: |
        docker-compose run app bundle exec rspec
